name: bluebubbles
description: Send iMessages on Android using BlueBubbles!

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.2.0

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^3.25.6
  shared_preferences: ^0.5.12
  socket_io_client: ^2.0.0-beta.3
  qr_code_scanner: ^0.3.5
  connectivity: ^2.0.2
  tuple: ^1.0.3
  encrypt: ^4.1.0
  assorted_layout_widgets: ^3.0.1
  record: ^1.0.3
  contacts_service:
    path: packages/flutter_contacts
  permission_handler: ^5.1.0+2
  path_provider: ^1.6.7
  sqflite: ^1.3.0
  path: ">=1.6.2 <2.0.0"
  intl: ^0.16.1
  flutter_svg: ^0.18.0
  intent: ^1.3.4
  photo_manager: ^0.6.0
  video_player: ^1.0.1
  assets_audio_player: ^2.0.1+9
  mime_type: ^0.3.1
  receive_sharing_intent: ^1.4.0+2
  flutter_map: ^0.11.0
  vcard_parser: ^0.1.6
  video_thumbnail: ^0.2.1
  camera: ^0.7.0+4
  android_intent: ^0.3.7+2
  flutter_slidable: ^0.5.7
  image_size_getter: ^0.3.0
  photo_view:
    path: packages/photo_view-0.9.2
  logger: ^0.9.1
  adaptive_theme: ^0.1.1
  sprung: ^1.1.0+11
  slugify: ^1.0.0
  metadata_fetch: ^0.3.3
  clipboard: ^0.1.2+8
  fluttertoast: ^6.0.1
  map_launcher: ^1.1.2
  flutter_colorpicker: ^0.3.4
  image_gallery_saver: ^1.6.8
  flutter_image_compress: ^0.7.0
  extended_text_field:
    path: packages/extended_text_field
  visibility_detector: ^0.1.5
  flutter_displaymode: ^0.1.1
  flutter_libphonenumber: ^0.3.11
  flutter_markdown: ^0.5.1
  keyboard_attachable: ^1.0.3
  device_info: ^1.0.0
  flutter_smart_reply: ^0.0.2
  faker: ^1.3.0
  emojis: ^0.9.3

dev_dependencies:
  build_runner: ^1.6.5
  build_verify: ^1.1.0
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

#   flutter_test:
#     sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # fonts:
  # - family: AppleColorEmoji
  #   fonts:
  #     - asset: assets/fonts/AppleColorEmoji.ttf

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/reactions/dislike-white.svg
    - assets/reactions/like-white.svg
    - assets/reactions/emphasize-white.svg
    - assets/reactions/question-white.svg
    - assets/reactions/love-white.svg
    - assets/reactions/dislike-black.svg
    - assets/reactions/like-black.svg
    - assets/reactions/emphasize-black.svg
    - assets/reactions/laugh-black.svg
    - assets/reactions/question-black.svg
    - assets/reactions/love-black.svg
    - assets/icon/moon.svg
    - assets/icon/discord.svg
    - assets/images/person.png
    - assets/images/person64.png
    - assets/icon/icon.png
    - assets/changelog/changelog.md
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
