name: bluebubbles
description: Send iMessages on Android using BlueBubbles!

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.6.0+17
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.3.8
  cupertino_icons: ^1.0.3
  exif: ^3.0.0
  flutter_native_image: ^0.0.6+1 # mobile only
  socket_io_client: ^2.0.0-beta.4-nullsafety.0
  url_launcher: ^6.0.9
  qr_code_scanner: ^0.5.2 # mobile only
  connectivity_plus: ^1.1.0
  tuple: ^2.0.0
  encrypt: ^5.0.1
  assorted_layout_widgets: # todo upgrade to actual package once their flutter 2.5 fix is merged
    git:
      url: https://github.com/josh-burton/assorted_layout_widgets
      ref: beta-fix
  record: ^3.0.0 # mobile and web
  fast_contacts: ^1.1.0 # mobile only
  permission_handler: ^8.1.4+2 # mobile only, todo disable on desktop
  path_provider: ^2.0.2 # no web support
  sqflite: ^2.0.0+3 # mobile only
  sqflite_common_ffi: ^2.0.0+3 # desktop
  path: ^1.8.0
  intl: ^0.17.0
  flutter_svg: ^0.22.0 # partial web support
  photo_manager: ^1.3.1 # only mobile
  video_player: ^2.1.13 # no desktop support, todo desktop
  chewie_audio: # no desktop support, todo desktop
    git:
      url: https://github.com/tneotia/chewie_audio-1.git
      ref: BlueBubbles
  mime_type: ^1.0.0
  receive_sharing_intent: ^1.4.5 # mobile only
  flutter_map: ^0.13.1
  video_thumbnail: ^0.4.3 # mobile only, todo disable on desktop
  flutter_slidable: ^0.6.0
  image_size_getter: ^1.0.0
  photo_view: ^0.12.0
  adaptive_theme: ^2.2.0
  sprung: ^3.0.0
  slugify: ^2.0.0
  metadata_fetch: ^0.4.1
  maps_launcher: ^2.0.1
  latlong2: ^0.8.0
  smooth_page_indicator: ^1.0.0+2
  flex_color_picker: ^2.1.2
  image_gallery_saver: ^1.6.9 # mobile only, todo download differently on desktop
  visibility_detector: ^0.2.0
  flutter_displaymode: ^0.3.2 # android only
  libphonenumber_plugin: ^0.2.3 # no desktop support, todo desktop
  flutter_libphonenumber: ^1.2.1 # no web or desktop support, used to speed up chat loading on mobile
  flutter_markdown: ^0.6.4
  device_info_plus: ^2.1.0
  google_ml_kit: ^0.7.0 # mobile only
  faker: ^2.0.0
  share_plus: ^2.1.4 # sharing files not supported on Windows & Linux, todo desktop
  # for nullsafety
  battery_optimization: # android only
    git:
      url: https://github.com/ChangJoo-Park/battery_optimization
      ref: master
  collection: ^1.15.0
  internet_connection_checker: ^0.0.1+2 # no web support, but we don't need it obviously
  secure_application: ^3.7.3 # no linux support
  local_auth: ^1.1.6 # mobile only
  flutter_screen_lock: ^4.0.4+1
  crop_your_image: ^0.6.0+1
  chewie: ^1.2.2 # no desktop support, todo desktop
  simple_animations: ^3.1.1
  flutter_keyboard_visibility: ^5.0.3 # no desktop support, todo desktop
  flutter_local_notifications: ^8.1.1+2 # mobile only
  flutter_native_timezone: ^2.0.0 # no desktop support
  package_info_plus: ^1.0.6
  shared_preferences: ^2.0.7
  location: ^4.3.0 # no desktop support, todo desktop
  universal_io: ^2.0.4 # cross-platform dart:io implementation
  universal_html: ^2.0.8 # cross-platform dart:html implementation
  file_picker: ^4.0.2
  firebase_dart: ^1.0.0-dev.45
  dio_http: ^5.0.4
  flutter_dropzone: ^2.0.1
  transparent_pointer: ^1.0.0
  quick_notify: ^0.1.0+2
  qr_flutter: ^4.0.0
  window_manager: ^0.0.4
  objectbox: ^1.2.0
  objectbox_flutter_libs: any

dependency_overrides:
  rxdart: ^0.27.2

dev_dependencies:
  build_runner: ^2.1.1
  build_verify: ^2.0.0
  flutter_launcher_icons: ^0.9.1
  flutter_native_splash: ^1.2.1
  msix: ^2.1.3
  peanut: ^4.0.1
  objectbox_generator: any
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon/icon.png"
  adaptive_icon_foreground: "assets/icon/adaptive-foreground.png"
  adaptive_icon_background: "#4990de"

flutter_native_splash:
  color: "#4990de"
  color_dark: "#000000"
  image: "assets/icon/splash-foreground-light.png"
  image_dark: "assets/icon/splash-foreground-dark.png"
  android12: true

#   flutter_test:
#     sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # fonts:
  # - family: AppleColorEmoji
  #   fonts:
  #     - asset: assets/fonts/AppleColorEmoji.ttf

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/reactions/dislike-white.svg
    - assets/reactions/like-white.svg
    - assets/reactions/emphasize-white.svg
    - assets/reactions/question-white.svg
    - assets/reactions/love-white.svg
    - assets/reactions/dislike-black.svg
    - assets/reactions/like-black.svg
    - assets/reactions/emphasize-black.svg
    - assets/reactions/laugh-black.svg
    - assets/reactions/question-black.svg
    - assets/reactions/love-black.svg
    - assets/icon/moon.svg
    - assets/icon/discord.svg
    - assets/images/person.png
    - assets/images/person64.png
    - assets/icon/icon.png
    - assets/changelog/changelog.md
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

msix_config:
  display_name: BlueBubbles
  publisher_display_name: BlueBubbles Development Team
  identity_name: com.bluebubbles.app
  msix_version: 1.0.0.6
  publisher: CN=BlueBubbles, O=BlueBubbles, C=US
  vs_generated_images_folder_path: windows/icons
  icons_background_color: transparent
  languages: en-us # todo
  architecture: x64 # todo
  capabilities: internetClient, location, microphone, webcam # todo