name: bluebubbles
description: Send iMessages on Android using BlueBubbles!

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.11.0+41
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  adaptive_theme: ^3.1.1
  animated_size_and_fade: ^3.0.0
  animations: ^2.0.7
  async_task: ^1.0.18
  audio_waveforms: ^0.1.5+1
  auto_size_text: ^3.0.0
  bitsdojo_window:
    git:
      url: https://github.com/jjoelj/bitsdojo_window.git
      ref: 5317458a49240217931f749f700107b268bebf24
      path: bitsdojo_window
  chewie: ^1.3.5 # no desktop support, todo desktop
  chunked_stream: ^1.4.1
  collection: ^1.16.0
  confetti: ^0.7.0
  connectivity_plus: ^2.3.6+1
  crop_your_image: ^0.7.2
  cupertino_icons: ^1.0.5
  dart_vlc: ^0.3.0
  defer_pointer: ^0.0.2
  desktop_drop: ^0.3.3
  device_info_plus: ^4.1.2
  dio: ^4.0.6
  disable_battery_optimization: ^1.1.0+1
  dynamic_color: ^1.4.0
  emojis: ^0.9.9
  encrypt: ^5.0.1
  exif: ^3.1.2
  faker: ^2.0.0
  fast_contacts: ^1.1.1 # mobile only
  file_picker: ^5.0.1
  firebase_dart: ^1.0.10+1
  flex_color_picker: ^2.5.0
  flex_color_scheme: ^5.1.0
  flutter_acrylic: ^1.0.0+2
  flutter_contacts: ^1.1.5+1
  flutter_displaymode: ^0.4.0 # android only
  flutter_dotenv: ^5.0.2
  flutter_improved_scrolling: ^0.0.3
  flutter_isolate: ^2.0.3
  flutter_keyboard_visibility: ^5.3.0 # no desktop support
  flutter_libphonenumber: ^1.2.4 # no web or desktop support, used to speed up chat loading on mobile
  flutter_local_notifications: ^9.7.1 # mobile only
  flutter_map: ^3.0.0
  flutter_map_marker_popup: ^4.0.0
  flutter_markdown: ^0.6.10+3
  flutter_native_image: ^0.0.6+1 # mobile only
  flutter_native_timezone: ^2.0.0 # no desktop support
  flutter_slidable: ^2.0.0
  flutter_staggered_grid_view: ^0.6.2
  flutter_svg: ^1.1.3
  geolocator: 8.2.1
  get: 4.3.8 # pinned because of snackbar issue
  giphy_get: ^3.1.0
  github: ^9.7.0
  google_fonts: ^3.0.1
  google_ml_kit: ^0.12.0 # mobile only
  hand_signature: ^2.3.0+1
  idb_shim: ^2.0.1+1
  image: ^3.2.0
  image_gallery_saver: ^1.7.1 # mobile only
  image_picker: ^0.8.5+3
  image_size_getter: ^2.1.2
  intl: ^0.17.0
  js: ^0.6.4
  launch_at_startup: ^0.2.0
  libphonenumber_plugin: ^0.2.3 # no desktop support, todo desktop
  local_auth: ^2.1.2 # mobile only, todo windows
  local_notifier:
    git:
      url: https://github.com/BlueBubblesApp/local_notifier.git
      ref: d1d236e39e9bdf517dea32da36bed927dea18cdf
  maps_launcher: ^2.0.1
  material_color_utilities: ^0.2.0
  metadata_fetch: ^0.4.1
  mime_type: ^1.0.0
  mobile_scanner: ^2.0.0 # no desktop support
  multi_value_listenable_builder: ^0.0.2
  network_info_plus: 2.1.4+1
  network_tools: ^3.0.0+3
  numberpicker: ^2.1.1
  objectbox: ^1.6.0
  objectbox_flutter_libs: any
  open_filex: 4.1.1
  package_info_plus: ^1.4.3+1
  particles_flutter: ^0.1.4
  pasteboard: ^0.2.0
  path: ^1.8.2
  path_provider: ^2.0.11 # no web support
  pdf: ^3.8.2
  permission_handler: ^9.2.0 # mobile only
  photo_manager: ^2.2.0 # only mobile
  photo_view: ^0.14.0
  printing: ^5.9.2
  qr_flutter:
    git:
      url: https://github.com/theyakka/qr.flutter
      ref: master
  quick_notify: ^0.2.0
  receive_intent: ^0.2.3 # mobile only
  receive_sharing_intent: ^1.4.5
  reorderables: ^0.5.0
  screen_retriever: ^0.1.4
  scroll_to_index: ^3.0.1
  secure_application: ^3.8.0 # no linux support
  share_plus: ^4.0.10+1 # sharing files not supported on Windows & Linux, todo desktop
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  simple_animations: ^5.0.0+2
  slugify: ^2.0.0
  smooth_page_indicator: ^1.0.0+2
  socket_io_client: ^2.0.0
  sprung: ^3.0.1
  store_checker: ^1.1.0
  supercharged: ^2.1.1
  system_tray: ^2.0.1
  tuple: ^2.0.0
  universal_html: ^2.0.8 # cross-platform dart:html implementation
  universal_io: ^2.0.4 # cross-platform dart:io implementation
  url_launcher: ^6.1.5
  version: ^3.0.2
  video_player: ^2.4.6 # no desktop support, todo desktop
  video_thumbnail: ^0.5.2 # mobile only
  window_manager: ^0.2.5
  windows_taskbar: ^1.1.0+1

dependency_overrides:
  ffi: ^2.0.1
  geolocator_windows:
    git:
      url: https://github.com/BlueBubblesApp/flutter-geolocator.git
      ref: 0b697a937422174cc01c92c6da7eebadc708a4c3
      path: geolocator_windows
  material_color_utilities: ^0.2.0 # flutter test SDK depends on 0.1.4
  path: ^1.8.2 # flutter test SDK depends on 1.8.1
  rxdart: ^0.27.5

dev_dependencies:
  build_runner: ^2.2.0
  build_verify: ^3.0.0
  flutter_launcher_icons: ^0.10.0
  flutter_native_splash: ^2.2.7
  flutter_lints: ^2.0.1
  msix: ^3.6.3
  peanut: ^4.3.0
  objectbox_generator: any
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon/icon.png"
  adaptive_icon_foreground: "assets/icon/adaptive-foreground.png"
  adaptive_icon_background: "#4990de"

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#000000"
  image: "assets/icon/splash-foreground-dark.png"
  image_dark: "assets/icon/splash-foreground-dark.png"
  android_12:
    image: "assets/icon/splash-foreground-dark-2.png"
    image_dark: "assets/icon/splash-foreground-dark-2.png"
    icon_background_color: "#FFFFFF"
    icon_background_color_dark: "000000"

#   flutter_test:
#     sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # fonts:
  # - family: AppleColorEmoji
  #   fonts:
  #     - asset: assets/fonts/AppleColorEmoji.ttf

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/reactions/dislike-white.svg
    - assets/reactions/like-white.svg
    - assets/reactions/emphasize-white.svg
    - assets/reactions/question-white.svg
    - assets/reactions/love-white.svg
    - assets/reactions/dislike-black.svg
    - assets/reactions/like-black.svg
    - assets/reactions/emphasize-black.svg
    - assets/reactions/laugh-black.svg
    - assets/reactions/question-black.svg
    - assets/reactions/love-black.svg
    - assets/icon/moon.svg
    - assets/icon/discord.svg
    - assets/images/person.png
    - assets/images/person64.png
    - assets/images/transparent.png
    - assets/images/no-video-preview.png
    - assets/images/unplayable-video.png
    - assets/icon/icon.png
    - assets/changelog/changelog.md
    - assets/icon/icon.ico
    - assets/badges/badge-1.ico
    - assets/badges/badge-2.ico
    - assets/badges/badge-3.ico
    - assets/badges/badge-4.ico
    - assets/badges/badge-5.ico
    - assets/badges/badge-6.ico
    - assets/badges/badge-7.ico
    - assets/badges/badge-8.ico
    - assets/badges/badge-9.ico
    - assets/badges/badge-10.ico
    - .env
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

msix_config:
  display_name: BlueBubbles
  publisher_display_name: BlueBubbles
  identity_name: 23344BlueBubbles.BlueBubbles
  msix_version: 1.10.100.0
  publisher: CN=BEC9154D-191E-4375-BF30-698BD4C141C4
  vs_generated_images_folder_path: windows/icons
  logo_path: assets/icon/icon.ico
  store: true
  #  certificate_path: ../bluebubbles.pfx
  #  certificate_password: BlueBubbles
  icons_background_color: transparent
  languages: en-us
  architecture: x64
  capabilities: internetClient, location, microphone, webcam
