name: bluebubbles
description: Send iMessages on Android using BlueBubbles!

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

version: 1.12.4+58
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  adaptive_theme: ^3.3.0
  animated_size_and_fade: ^3.0.1
  animations: ^2.0.7
  app_links: ^3.4.2
  async_task: ^1.0.20
  audio_waveforms: ^1.0.3
  auto_size_text: ^3.0.0
  bitsdojo_window: ^0.1.5
  chewie: ^1.7.0 # no desktop support, todo desktop
  chunked_stream: ^1.4.1
  collection: ^1.18.0
  confetti: ^0.7.0
  connectivity_plus: ^4.0.2
  crop_your_image: ^0.7.5
  csslib: ^1.0.0
  cupertino_icons: ^1.0.5
  defer_pointer: ^0.0.2
  desktop_drop: ^0.4.3
  desktop_webview_auth:
    git:
      url: https://github.com/BlueBubblesApp/flutter_desktop_webview_auth.git
      ref: webkit2gtk-4.1
  device_info_plus: ^9.0.3
  dio: ^5.3.2
  disable_battery_optimization: ^1.1.0+1
  # todo linux
  dynamic_color: ^1.6.6
  emojis: ^0.9.9
  encrypt: ^5.0.1
  exif: ^3.1.2
  faker: ^2.1.0
  fast_contacts: ^3.0.3 # mobile only
  file_picker: ^5.3.4
  firebase_dart:
    git:
      url: https://github.com/appsup-dart/firebase_dart.git
      ref: feature/firestore
      path: packages/firebase_dart
  flex_color_picker: ^3.3.0
  flex_color_scheme: ^7.3.1
  flutter_acrylic: ^1.1.3
  flutter_audio_waveforms: ^1.2.1+8
  # for vcard parsing only
  flutter_contacts: ^1.1.7+1
  flutter_displaymode: ^0.6.0 # android only
  flutter_dotenv: ^5.1.0
  flutter_foreground_task: ^6.1.1
  flutter_improved_scrolling: ^0.0.3
  flutter_isolate: ^2.0.3
  flutter_keyboard_visibility: ^5.4.0 # no desktop support
  flutter_local_notifications: ^15.1.1 # mobile only
  flutter_map: ^5.0.0
  flutter_map_marker_popup: ^5.1.0
  flutter_markdown: ^0.6.17+1
  flutter_native_image: ^0.0.6+1 # mobile only
  flutter_slidable: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.7
  flutter_timezone: ^1.0.7 # no desktop support
  geolocator:
    git:
      url: https://github.com/BlueBubblesApp/flutter-geolocator.git
      path: geolocator
      ref: no_windows_streams
  gesture_x_detector: ^1.1.1
  get: ^4.6.5
  giphy_get: ^3.5.0
  github: ^9.17.0
  google_fonts: ^5.1.0
  google_ml_kit: ^0.16.2 # mobile only
  google_sign_in: ^6.1.4
  hand_signature: ^3.0.1
  idb_shim: ^2.3.0+2
  image: ^4.0.15
  image_gallery_saver: ^2.0.3 # mobile only
  image_picker: ^1.0.2
  image_size_getter: ^2.1.2
  intl: ^0.18.0
  js: ^0.6.7
  launch_at_startup: ^0.2.2
  local_auth: ^2.1.6
  local_notifier:
    git:
      url: https://github.com/BlueBubblesApp/local_notifier.git
      ref: a8fbca6a7805487df725fbd2487e719202fcd209
  maps_launcher: ^2.2.0
  material_color_utilities: ^0.8.0
  media_kit: ^1.1.6                              # Primary package.
  media_kit_video: ^1.1.6                        # For video rendering.
  media_kit_native_event_loop: ^1.0.7            # Support for higher number of concurrent instances & better performance.
  media_kit_libs_windows_video: ^1.0.8           # Windows package for video native libraries.
  media_kit_libs_linux: ^1.1.2                   # GNU/Linux dependency package.
  metadata_fetch: ^0.4.1
  mime_type: ^1.0.0
  mobile_scanner: ^3.4.1 # no desktop support
  msix: ^3.9.2
  multi_value_listenable_builder: ^0.0.2
  network_info_plus: ^4.0.2
  network_tools: ^3.2.1
  numberpicker: ^2.1.1
  objectbox: ^2.2.1
  objectbox_flutter_libs: any
  on_exit: ^1.0.0
  open_filex: ^4.3.2
  package_info_plus: ^4.0.2
  particles_flutter: ^0.1.4
  pasteboard: ^0.2.0
  path: ^1.8.3
  path_provider: ^2.0.15 # no web support
  pdf: ^3.9.0
  permission_handler: ^10.4.3 # mobile only
  phone_numbers_parser: ^8.0.0
  photo_manager: ^2.7.1 # only mobile
  photo_view: ^0.14.0
  printing: ^5.10.4
  qr_flutter:
    git:
      url: https://github.com/theyakka/qr.flutter
      ref: master
  receive_intent: ^0.2.3 # mobile only
  record: ^4.4.4
  reorderables: ^0.6.0
  screen_retriever: ^0.1.6
  scroll_to_index: ^3.0.1
  secure_application: ^3.8.0 # no linux support
  share_plus: ^7.1.0 # sharing files not supported on Windows & Linux, todo desktop
  shared_preferences: ^2.2.0
  shimmer: ^3.0.0
  simple_animations: ^5.0.2
  slugify: ^2.0.0
  smooth_page_indicator: ^1.0.1
  socket_io_client: ^2.0.3+1
  sprung: ^3.0.1
  store_checker: ^1.4.0
  synchronized: ^3.0.1
  supercharged: ^2.1.1
  system_tray: ^2.0.3
  tuple: ^2.0.2
  universal_html: ^2.2.3 # cross-platform dart:html implementation
  universal_io: ^2.2.2 # cross-platform dart:io implementation
  url_launcher: ^6.1.12
  version: ^3.0.2
  video_player: ^2.7.0
  video_thumbnail: ^0.5.3 # mobile only
  window_manager: ^0.3.5
  windows_taskbar: ^1.1.1
  window_to_front: ^0.0.3

dependency_overrides:
  # overrides for packages stuck on outdated versions
  collection: ^1.18.0 # flutter test SDK
  material_color_utilities: ^0.8.0 # flutter test SDK
  intl: ^0.18.1 # network_tools
  rxdart: ^0.27.7 # secure_application
  package_info_plus: ^4.0.2 # BB geolocator
  win32: ^5.0.6 # bitsdojo
  csslib: ^1.0.0 # universal_html
  http: ^1.0.0 # metadata_fetch
  permission_handler_windows:
    git:
      url: https://github.com/BlueBubblesApp/flutter-permission-handler.git
      ref: no_windows_location
      path: permission_handler_windows

dev_dependencies:
  build_runner: ^2.4.6
  build_verify: ^3.1.0
  flutter_launcher_icons: ^0.13.0
  flutter_native_splash: ^2.3.2
  flutter_lints: ^2.0.2
  peanut: ^5.0.0
  objectbox_generator: any
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon/icon.png"
  adaptive_icon_foreground: "assets/icon/adaptive-foreground.png"
  adaptive_icon_background: "#4990de"

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#000000"
  image: "assets/icon/splash-foreground-dark.png"
  image_dark: "assets/icon/splash-foreground-dark.png"
  android_12:
    image: "assets/icon/splash-foreground-dark-2.png"
    image_dark: "assets/icon/splash-foreground-dark-2.png"
    icon_background_color: "#FFFFFF"
    icon_background_color_dark: "000000"

#   flutter_test:
#     sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # fonts:
  # - family: AppleColorEmoji
  #   fonts:
  #     - asset: assets/fonts/AppleColorEmoji.ttf

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/reactions/dislike-white.svg
    - assets/reactions/like-white.svg
    - assets/reactions/emphasize-white.svg
    - assets/reactions/question-white.svg
    - assets/reactions/love-white.svg
    - assets/reactions/dislike-black.svg
    - assets/reactions/like-black.svg
    - assets/reactions/emphasize-black.svg
    - assets/reactions/laugh-black.svg
    - assets/reactions/question-black.svg
    - assets/reactions/love-black.svg
    - assets/icon/moon.svg
    - assets/icon/discord.svg
    - assets/images/google-sign-in.png
    - assets/images/person.png
    - assets/images/person64.png
    - assets/images/transparent.png
    - assets/images/no-video-preview.png
    - assets/images/unplayable-video.png
    - assets/icon/icon.png
    - assets/changelog/changelog.md
    - assets/icon/icon.ico
    - assets/badges/badge-1.ico
    - assets/badges/badge-2.ico
    - assets/badges/badge-3.ico
    - assets/badges/badge-4.ico
    - assets/badges/badge-5.ico
    - assets/badges/badge-6.ico
    - assets/badges/badge-7.ico
    - assets/badges/badge-8.ico
    - assets/badges/badge-9.ico
    - assets/badges/badge-10.ico
    - .env
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

msix_config:
  display_name: BlueBubbles
  publisher_display_name: BlueBubbles
  identity_name: 23344BlueBubbles.BlueBubbles
  msix_version: 1.12.4.0
  publisher: CN=BEC9154D-191E-4375-BF30-698BD4C141C4
  vs_generated_images_folder_path: windows/icons
  logo_path: assets/icon/icon.ico
  store: true
  #  certificate_path: ../bluebubbles.pfx
  #  certificate_password: BlueBubbles
  icons_background_color: transparent
  languages: en-us
  architecture: x64
  capabilities: internetClient, location, microphone, webcam
  protocol_activation: imessage
