name: bluebubbles
description: Send iMessages on Android using BlueBubbles!

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.3.0
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.2.1+1
  cupertino_icons: ^1.0.3
  exif: ^3.0.0
  flutter_native_image: ^0.0.6+1
  shared_preferences: ^2.0.6
  socket_io_client: ^1.0.1
  url_launcher: ^6.0.9
  qr_code_scanner: ^0.5.2
  connectivity: ^3.0.6
  tuple: ^2.0.0
  encrypt: ^5.0.0
  assorted_layout_widgets: ^5.0.2
  record: ^3.0.0
  contacts_service: ^0.6.1
  permission_handler: ^8.1.3
  path_provider: ^2.0.2
  sqflite: ^2.0.0+3
  path: ^1.8.0
  intl: ^0.17.0
  flutter_svg: ^0.22.0
  photo_manager: ^1.2.7
  video_player: ^2.1.10
  chewie_audio:
    git:
      url: https://github.com/tneotia/chewie_audio-1.git
      ref: BlueBubbles
  mime_type: ^1.0.0
  receive_sharing_intent: ^1.4.5
  flutter_map: ^0.13.1
  video_thumbnail: ^0.3.3
  camera: ^0.8.1+5
  android_intent: ^2.0.2
  flutter_slidable: ^0.6.0
  image_size_getter: ^1.0.0
  photo_view: ^0.12.0
  logger: ^1.0.0
  adaptive_theme: ^2.2.0
  sprung: ^3.0.0
  slugify: ^2.0.0
  metadata_fetch: ^0.4.1
  clipboard: ^0.1.3
  fluttertoast: ^8.0.7
  map_launcher: ^2.1.1
  latlong2: ^0.8.0
  smooth_page_indicator: ^0.3.0-nullsafety.0
  # Pinned to 0.4.0 for now because Flutter 2 stable doesn't support the stuff in 0.5.0 yet
  flutter_colorpicker: ^0.4.0
  image_gallery_saver: ^1.6.9
  visibility_detector: ^0.2.0
  flutter_displaymode: ^0.3.2
  flutter_libphonenumber: ^1.1.0
  flutter_markdown: ^0.6.2
  device_info: ^2.0.2
  google_ml_kit: ^0.6.0
  faker: ^2.0.0
  share_plus: ^2.1.4
  # for nullsafety
  battery_optimization:
    git:
      url: https://github.com/ChangJoo-Park/battery_optimization
      ref: master
  collection: ^1.15.0
  internet_connection_checker: ^0.0.1+2
  secure_application: ^3.7.3
  local_auth: ^1.1.6
  flutter_screen_lock: ^4.0.4+1
  image: ^3.0.2

dev_dependencies:
  build_runner: ^2.0.6
  build_verify: ^2.0.0
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^1.1.8+4

dependency_overrides:
  rxdart: ^0.27.0

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon/icon.png"
  adaptive_icon_foreground: "assets/icon/adaptive-foreground.png"
  adaptive_icon_background: "#4990de"

flutter_native_splash:
  color: "#4990de"
  color_dark: "#000000"
  image: "assets/icon/splash-foreground-light.png"
  image_dark: "assets/icon/splash-foreground-dark.png"

#   flutter_test:
#     sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # fonts:
  # - family: AppleColorEmoji
  #   fonts:
  #     - asset: assets/fonts/AppleColorEmoji.ttf

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/reactions/dislike-white.svg
    - assets/reactions/like-white.svg
    - assets/reactions/emphasize-white.svg
    - assets/reactions/question-white.svg
    - assets/reactions/love-white.svg
    - assets/reactions/dislike-black.svg
    - assets/reactions/like-black.svg
    - assets/reactions/emphasize-black.svg
    - assets/reactions/laugh-black.svg
    - assets/reactions/question-black.svg
    - assets/reactions/love-black.svg
    - assets/icon/moon.svg
    - assets/icon/discord.svg
    - assets/images/person.png
    - assets/images/person64.png
    - assets/icon/icon.png
    - assets/changelog/changelog.md
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
