name: bluebubbles
description: Send iMessages on Android using BlueBubbles!

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.9.0+29
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.3.8 # pinned because of snackbar issue
  cupertino_icons: ^1.0.4
  exif: ^3.1.1
  flutter_native_image: ^0.0.6+1 # mobile only
  socket_io_client: ^2.0.0-beta.4-nullsafety.0
  url_launcher: ^6.1.2
  mobile_scanner: ^1.1.0 # no desktop support
  connectivity_plus: ^2.3.0
  tuple: ^2.0.0
  encrypt: ^5.0.1
  assorted_layout_widgets: ^5.8.5
  record: ^4.1.1 # mobile and web
  fast_contacts: ^1.1.1 # mobile only
  permission_handler: ^9.2.0 # mobile only
  path_provider: ^2.0.10 # no web support
  sqflite: ^2.0.2+1 # mobile only
  sqflite_common_ffi: ^2.1.1 # desktop
  path: ^1.8.1
  intl: ^0.17.0
  flutter_svg: ^1.0.3
  photo_manager: ^2.1.0+2 # only mobile
  video_player: ^2.4.2 # no desktop support, todo desktop
  chewie_audio: # no desktop support, todo desktop
    git:
      url: https://github.com/tneotia/chewie_audio-1.git
      ref: BlueBubbles
  mime_type: ^1.0.0
  receive_sharing_intent: ^1.4.5 # mobile only
  flutter_map: ^0.14.0
  video_thumbnail: ^0.5.0 # mobile only
  flutter_slidable: ^1.2.0
  image_size_getter: ^2.1.1
  photo_view: ^0.13.0
  adaptive_theme: ^2.3.1
  sprung: ^3.0.0
  slugify: ^2.0.0
  metadata_fetch: ^0.4.1
  maps_launcher: ^2.0.1
  latlong2: ^0.8.1
  smooth_page_indicator: ^1.0.0+2
  flex_color_picker: ^2.5.0
  image_gallery_saver: ^1.7.1 # mobile only
  visibility_detector: ^0.3.3
  flutter_displaymode: ^0.4.0 # android only
  libphonenumber_plugin: ^0.2.3 # no desktop support, todo desktop
  flutter_libphonenumber: ^1.2.4 # no web or desktop support, used to speed up chat loading on mobile
  flutter_markdown: ^0.6.10
  device_info_plus: ^3.2.3
  google_ml_kit: ^0.11.0 # mobile only
  faker: ^2.0.0
  share_plus: ^4.0.4 # sharing files not supported on Windows & Linux, todo desktop
  collection: ^1.16.0
  disable_battery_optimization: ^1.1.0+1
  secure_application: ^3.8.0 # no linux support
  local_auth: ^2.0.2 # mobile only
  crop_your_image: ^0.7.2
  chewie: ^1.3.2 # no desktop support, todo desktop
  simple_animations: ^4.0.2
  flutter_keyboard_visibility: ^5.2.0 # no desktop support
  flutter_local_notifications: ^9.5.3+1 # mobile only
  flutter_native_timezone: ^2.0.0 # no desktop support
  package_info_plus: ^1.4.2
  shared_preferences: ^2.0.15
  location: ^4.4.0 # no desktop support, todo desktop
  universal_io: ^2.0.4 # cross-platform dart:io implementation
  universal_html: ^2.0.8 # cross-platform dart:html implementation
  file_picker: ^4.5.1
  firebase_dart: ^1.0.7
  dio: ^4.0.6
  flutter_dropzone: ^3.0.5
  transparent_pointer: ^1.0.0
  quick_notify: ^0.2.1
  qr_flutter: ^4.0.0
  window_manager: ^0.2.3
  objectbox: ^1.5.0
  objectbox_flutter_libs: any
  js: ^0.6.4
  bitsdojo_window:
    git:
      url: https://github.com/jjoelj/bitsdojo_window.git
      ref: 5317458a49240217931f749f700107b268bebf24
      path: bitsdojo_window
  system_tray:
    git:
      url: https://github.com/antler119/system_tray.git
      ref: 576d7cc17fbab10bcdb40468a0db012d2365462e
  flutter_improved_scrolling: ^0.0.3
  desktop_drop: ^0.3.3
  particles_flutter: ^0.1.4
  # used for percent progress when downloading font
  dynamic_cached_fonts:
    git:
      url: https://github.com/jjoelj/dynamic_cached_fonts
      ref: main
  confetti: ^0.7.0
  supercharged: ^2.1.1
  pdf: ^3.8.0
  printing: ^5.9.0
  shimmer: ^2.0.0
  giphy_get: ^3.0.5
  flutter_dotenv: ^5.0.2
  image: ^3.1.3
  launch_at_startup: ^0.1.7
  async_task: ^1.0.18
  filesystem_picker: ^2.0.0
  version: ^2.0.0
  emojis: ^0.9.9
  defer_pointer: ^0.0.2
  pasteboard: ^0.0.3
  win_toast:
    git:
      url: https://github.com/jjoelj/flutter-plugins.git
      ref: f64b90f651e8655a75568b0db67319ba48a5156a
      path: packages/win_toast
  dynamic_color: ^1.2.2
  material_color_utilities: ^0.1.5
  dart_vlc: ^0.2.1
  geolocator: ^8.2.1

dependency_overrides:
  rxdart: ^0.27.3
  path_parsing: ^1.0.0
  qr: 2.0.0 # qr_flutter depends on 2.0.0
  barcode: 2.1.0 # qr 2.0.0 depends on 2.1.0
  get: 4.3.8 # pinned because of snackbar issue
  material_color_utilities: ^0.1.5 # flutter test SDK depends on 0.1.4
  bitsdojo_window_linux:
    git:
      url: https://github.com/jjoelj/bitsdojo_window.git
      ref: 5317458a49240217931f749f700107b268bebf24
      path: bitsdojo_window_linux
  bitsdojo_window_macos:
    git:
      url: https://github.com/jjoelj/bitsdojo_window.git
      ref: 5317458a49240217931f749f700107b268bebf24
      path: bitsdojo_window_macos
  bitsdojo_window_windows:
    git:
      url: https://github.com/jjoelj/bitsdojo_window.git
      ref: 5317458a49240217931f749f700107b268bebf24
      path: bitsdojo_window_windows

dev_dependencies:
  build_runner: ^2.1.10
  build_verify: ^3.0.0
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.1.2+1
  flutter_lints: ^2.0.1
  msix: ^3.6.2
  peanut: ^4.1.1
  objectbox_generator: any
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon/icon.png"
  adaptive_icon_foreground: "assets/icon/adaptive-foreground.png"
  adaptive_icon_background: "#4990de"

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#000000"
  image: "assets/icon/splash-foreground-dark.png"
  image_dark: "assets/icon/splash-foreground-dark.png"
  android12:
    image: "assets/icon/splash-foreground-dark.png"
    image_dark: "assets/icon/splash-foreground-dark.png"
    icon_background_color: "#FFFFFF"
    icon_background_color_dark: "000000"

#   flutter_test:
#     sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # fonts:
  # - family: AppleColorEmoji
  #   fonts:
  #     - asset: assets/fonts/AppleColorEmoji.ttf

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/reactions/dislike-white.svg
    - assets/reactions/like-white.svg
    - assets/reactions/emphasize-white.svg
    - assets/reactions/question-white.svg
    - assets/reactions/love-white.svg
    - assets/reactions/dislike-black.svg
    - assets/reactions/like-black.svg
    - assets/reactions/emphasize-black.svg
    - assets/reactions/laugh-black.svg
    - assets/reactions/question-black.svg
    - assets/reactions/love-black.svg
    - assets/icon/moon.svg
    - assets/icon/discord.svg
    - assets/images/person.png
    - assets/images/person64.png
    - assets/images/transparent.png
    - assets/images/no-video-preview.png
    - assets/images/unplayable-video.png
    - assets/icon/icon.png
    - assets/changelog/changelog.md
    - assets/icon/icon.ico
    - .env
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

msix_config:
  display_name: BlueBubbles
  publisher_display_name: BlueBubbles
  identity_name: 23344BlueBubbles.BlueBubbles
  msix_version: 1.9.5.0
  publisher: CN=BEC9154D-191E-4375-BF30-698BD4C141C4
  vs_generated_images_folder_path: windows/icons
  logo_path: assets/icon/icon.ico
  store: true
#  certificate_path: ../bluebubbles.pfx
#  certificate_password: BlueBubbles
  icons_background_color: transparent
  languages: en-us
  architecture: x64
  capabilities: internetClient, location, microphone, webcam
